WIP to avoid dynamic cast, based on idea from HN user "vore".
"I think, at that point, you should rather make Wherr be `struct Wherr<E> { inner: E, ... }` to avoid having to do a dynamic cast - I don't personally like the idea of erasing guarantees of what types you're getting."

HN comment: https://news.ycombinator.com/item?id=37232229#37243015

Not sure if this is the right approach. The other idea of just using #[track_caller] is probably the right one.
But since that would break 0.1 compatability, maybe this idea is worth investigating, for the macro variant.

Current problems:

error[E0277]: the size for values of type `dyn std::error::Error` cannot be known at compilation time
  --> wherr/tests/integration_tests.rs:53:9
   |
53 |     f3()?;
   |         ^ doesn't have a size known at compile-time
   |
   = help: the trait `Sized` is not implemented for `dyn std::error::Error`
   = help: the following other types implement trait `FromResidual<R>`:
             <Result<T, F> as FromResidual<Result<Infallible, E>>>
             <Result<T, F> as FromResidual<Yeet<E>>>
   = note: required for `Box<dyn std::error::Error>` to implement `std::error::Error`
   = note: 1 redundant requirement hidden
   = note: required for `Wherr<Box<dyn std::error::Error>>` to implement `std::error::Error`
   = note: required for `Box<dyn std::error::Error>` to implement `From<Wherr<Box<dyn std::error::Error>>>`
   = note: required for `Result<(), Box<dyn std::error::Error>>` to implement `FromResidual<Result<Infallible, Wherr<Box<dyn std::error::Error>>>>`

error[E0277]: the size for values of type `dyn std::error::Error` cannot be known at compilation time
  --> wherr/tests/integration_tests.rs:60:9
   |
60 |     f2()?;
   |         ^ doesn't have a size known at compile-time
   |
   = help: the trait `Sized` is not implemented for `dyn std::error::Error`
   = help: the following other types implement trait `FromResidual<R>`:
             <Result<T, F> as FromResidual<Result<Infallible, E>>>
             <Result<T, F> as FromResidual<Yeet<E>>>
   = note: required for `Box<dyn std::error::Error>` to implement `std::error::Error`
   = note: 1 redundant requirement hidden
   = note: required for `Wherr<Box<dyn std::error::Error>>` to implement `std::error::Error`
   = note: required for `Box<dyn std::error::Error>` to implement `From<Wherr<Box<dyn std::error::Error>>>`
   = note: required for `Result<(), Box<dyn std::error::Error>>` to implement `FromResidual<Result<Infallible, Wherr<Box<dyn std::error::Error>>>>`

error[E0107]: missing generics for struct `Wherr`
  --> wherr/tests/integration_tests.rs:70:40
   |
70 |             let wherr = err.downcast::<Wherr>().expect("Expected a Wherr error");
   |                                        ^^^^^ expected 1 generic argument
   |
note: struct defined here, with 1 generic parameter: `E`
  --> /Users/joel/src/wherr/wherr/src/lib.rs:16:12
   |
16 | pub struct Wherr<E> {
   |            ^^^^^ -
help: add missing generic argument
   |
70 |             let wherr = err.downcast::<Wherr<E>>().expect("Expected a Wherr error");
   |                                             +++

error[E0277]: the size for values of type `dyn std::error::Error` cannot be known at compilation time
  --> wherr/examples/with_wherr.rs:14:41
   |
14 |     let foo = concat_files(path1, path2)?;
   |                                         ^ doesn't have a size known at compile-time
   |
   = help: the trait `Sized` is not implemented for `dyn std::error::Error`
   = help: the following other types implement trait `FromResidual<R>`:
             <Result<T, F> as FromResidual<Result<Infallible, E>>>
             <Result<T, F> as FromResidual<Yeet<E>>>
   = note: required for `Box<dyn std::error::Error>` to implement `std::error::Error`
   = note: 1 redundant requirement hidden
   = note: required for `Wherr<Box<dyn std::error::Error>>` to implement `std::error::Error`
   = note: required for `Box<dyn std::error::Error>` to implement `From<Wherr<Box<dyn std::error::Error>>>`
   = note: required for `Result<String, Box<dyn std::error::Error>>` to implement `FromResidual<Result<Infallible, Wherr<Box<dyn std::error::Error>>>>`

Some errors have detailed explanations: E0107, E0277.
For more information about an error, try `rustc --explain E0107`.
For more information about this error, try `rustc --explain E0277`.
error: could not compile `wherr` due to 3 previous errors
warning: build failed, waiting for other jobs to finish...
error: could not compile `wherr` due to previous error